## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    # 强制告诉 waf：dash/examples 依赖 lte 和 epc
    # bld.env.NS3_MODULES = bld.env.NS3_MODULES + ['lte', 'epc']

    obj = bld.create_ns3_program('avp2pTest',
                                 ['dash', 'internet', 'applications',
                                  'point-to-point'])
    obj.source = 'avp2pTest.cc'
